### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Orbyt** [AVGP/terminal.js#5]
I have everything implemented but commands dont seem to work. Site im trying to use it on is http://orbyt.me

In the terminal.js file, i added: 

``` javascript
commands.help = function(args) {
        return "<p>Welcome to the <span style=\"color: #0f0; font-weight: bold\">Geekonaut</span> terminal</p>" +
               "<p>Here is what you can do:</p>";
    };
```

my html for the terminal:

``` html
<div id="terminal">
    <p>
        <span class="prompt">guest@orbyt.me &gt; </span>
        <span contenteditable="true" class="input"> </span>
    </p>
</div>
```

and at the bottom of my `<body>` tag i have:

``` html
<script>
    terminal.init(document.getElementById("terminal"));
</script>
```

I also have the terminal.js file linked in my `<head>` tag properly. Any ideas?

**EDIT:** I made a codepen and linked the terminal.js and terminal.css from the demo, the codepen is here: http://codepen.io/orbyt/pen/rxmrwB. This seems to have the same issue as im having with my site.

Strangely, obviously the demo and your terminal on your site is working fine, so im not sure whats going wrong.

**Comment by AVGP** [comment]
Hey and thanks for using terminal.js!

Yes, this still works - and the reason it doesn't work on your page is the small typo: `terminal.init` should be `Terminal.init` - notice the uppercase "T".

For Codepen: I think it fails due to the way it loads the javascript. I don't know enough about how codepen does it but it's not loaded when the `Terminal.init` happens - that's more a Codepen-specific thing than a problem with the code itself.

If you need anything else or if there's still a problem, let me know please!

Cheers and I hope you have a lot of fun :-)

**Comment by Orbyt** [comment]
@AVGP Hmm, still not working. I changed the typo, my html now looks like this:

``` html
<body>
        <div class="content">
            <div class="intro-wrapper">
                <span class="intro"></span>
            </div>

            <div id="terminal">
                    <span class="prompt">guest@orbyt.me &gt; </span>
                    <span contenteditable="true" class="input"> </span>
            </div>
        </div>

        <script>
            Terminal.init(document.getElementById("terminal"));
        </script>
    </body>
```

here is a gist of my current terminal.js file: https://gist.github.com/Orbyt/3b615bdf8d6182476e76

I opened up the console and noticed that I was getting a 

> Uncaught TypeError: Cannot use 'in' operator to search for 'help' in undefined

on line 117 in the above terminal.js. Im guessing its referring to `self.commands` being undefined, but im not sure why.

**Comment by Orbyt** [comment]
**Update:** So I got something working. I noticed that the demo on your site (https://github.com/AVGP/avgp.github.com/blob/master/javascripts/terminal.js) was using a slightly modified version of terminal.js.  In that version, the `self.init` function only takes 1 parameter, an element, where as the version of terminal.js linked in the repo takes 2 parameters in the `self.init` function, an element and an array of commands. This caused some confusion, so when I called `Terminal.init(document.getElementById("terminal"));` I was not supplying the secondary param, which was causing the above error. Changing that script to contain the commands array and passing it into the init function seemed to fix the issue:

``` html
<script>
            var commands = {};
            commands.help = function(args) {
             return "<p>Welcome to the <span style=\"color: #0f0; font-weight: bold\">Geekonaut</span> terminal</p>" +
               "<p>Here is what you can do:</p>";
             };
            Terminal.init(document.getElementById("terminal"), commands);
        </script>
```

I do however have another issue where after hitting enter on a command, command line doesnt show up, but im not sure how to fix. I will post a seperate issue. Let me know if you see any issues with the solution I posted above.

**Comment by AVGP** [comment]
Hm, that's surprising.

[I made this JSBin](http://jsbin.com/degoxipini/edit?html,output) using the [terminal.js](https://github.com/AVGP/terminal.js/blob/gh-pages/terminal.js) unmodified from this repository and it works.

Also the implementation in your page, orbyt.me, works for me now.
I will close this issue for now and continue the discussion in #6
