### ISSUE TITLE
Hitting enter on command runs command, but a new command line is not created.

### ISSUE THREAD

**Issue by Orbyt** [AVGP/terminal.js#6]
After hitting enter when running a command, the command is ran, but a new command line is not generated. You can test on the site(http://orbyt.me), and heres a quick screenie to show what I mean: http://prntscr.com/9o0yro

Heres an updated gist of my current terminal.js file: https://gist.github.com/Orbyt/ee795c54b02ee28f9405

Current html:

``` html
<body>
        <div class="content">
            <div class="intro-wrapper">
                <span class="intro"></span>
            </div>

            <div id="terminal">
                    <span class="prompt">guest@orbyt.me &gt; </span>
                    <span contenteditable="true" class="input"> </span>
            </div>
        </div>

        <script>
            var commands = {};
            commands.help = function(args) {
             return "<p>Welcome to the <span style=\"color: #0f0; font-weight: bold\">Geekonaut</span> terminal</p>" +
               "<p>Here is what you can do:</p>";
             };
            Terminal.init(document.getElementById("terminal"), commands);
        </script>
    </body>
```

Im assuming this has to do with the function that handles the enter key event, (line 98-111 on the above gist), but am not sure whats going wrong. Ideas?

**EDIT:** getting:

> Uncaught TypeError: Cannot read property 'cloneNode' of null

in the console, in the resetPrompt() function. It seems prompt.parentNode is null for some reason.

**EDIT2:** So adding an empty `<p>` tag around the `<span>` tags seems to have fixed the issue:

``` html
<div id="terminal">
    <p>
        <span class="prompt">guest@orbyt.me &gt; </span>
        <span contenteditable="true" class="input"> </span>
    </p>
</div>
```

so prompt.parentNode is no longer null and refers to `<p>`. Im not sure why this works, because if `<p>` wasnt there, wouldnt prompt.parentNode refer to the `<div>` with the id of "terminal" and therefore not be null?

**Comment by AVGP** [comment]
So it works now, right?

This little screen capture tells me it does:
![](http://i.imgur.com/PF77xo0.gif)

But, yes, you did uncover a horrible gap in documentation that I will fix now!
I indeed expect a `<p>` around the prompt line in all cases. Unfortunately this wasn't mentioned in the documentation anywhere - thanks for pointing out my silly mistake.

Regarding that error you saw, I am just as puzzled. The `parentNode` would be the terminal div in that case, but for some reason the browser returns `null` if the event target (i.e. the `.input` span) is a direct child of the terminal. I haven't found an isolated test case to demonstrate _why_ that is the case, though.

Anyway, the issue boils down to a gap in documentation and I'm sorry you had to figure this one out this way - thanks for reporting the issues!

**Comment by AVGP** [comment]
Closing this issue, if you encounter any further problems, feel free to comment here to get this reopened!

**Comment by Orbyt** [comment]
@AVGP Yep, working as expected. Yea the `<div>` being null is odd, not sure why its happening. May look into it later.
